media:
  output: /blog/articles/images

collections:
  - name: blog
    label: ブログ記事
    type: folder
    path: blog/articles

    fields:
      - name: title
        label: 記事のタイトル
        type: string
        required: true

      - name: date
        label: 公開日
        type: date
        required: true

      - name: body
        label: 記事の本文
        type: rich-text
        required: true
