# 1. 画像の保存先を「blog/articles/images」に指定
media:
  output: /blog/articles/images

# 2. ブログ管理画面の設定
collections:
  - name: blog
    label: ブログ記事
    description: ここからブログの記事を追加・編集できます。
    type: folder
    path: blog/articles # 記事データを保存するフォルダ
    format: html-frontmatter
    slug: "{{slug}}/index" # フォルダ/index.html の形式で保存（拡張子を消す仕組み）
    
    # 3. 入力フォームの項目
    fields:
      - name: title
        label: 記事のタイトル
        type: string
        required: true

      - name: date
        label: 公開日
        type: date
        required: true

      - name: image
        label: アイキャッチ画像
        type: image

      - name: body
        label: 記事の本文
        type: rich-text
        required: true
