paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
  blog:
    path: blog/articles
    icon: event_available
    disable_url: false
    output: true
    # 👇 🟢新しく記事を作ったとき、自動でEleventyに認識させるための設定を追加
    schemas:
      default:
        path: ''
        target_path: 'blog/articles/{title}.md'
    _defaults:
      blog:
        tags: blog
timezone: Asia/Tokyo
