paths:
  uploads: uploads
  static: ''
collections_config:
  pages:
    path: ''
    icon: wysiwyg
    disable_url: false
  blog:
    path: blog/articles
    icon: event_available
    disable_url: false
    output: true
    format: html-frontmatter
    extension: html
    schemas:
      default:
        path: ''
        target_path: 'blog/articles/{title}.html'
    _defaults:
      blog:
        tags: blog # 👈 自動でEleventy用に「blog」タグが裏で付きます
    
    # 🟢 ここに入力フォームの設定を追加しました！
    fields:
      - name: title
        label: 記事のタイトル
        type: string
        required: true

      - name: date
        label: 公開日
        type: date
        required: true

      - name: image
        label: アイキャッチ画像（URL）
        type: image

      - name: tags
        label: 追加のタグ（カンマ区切りで複数可）
        type: select
        allow_custom: true
        multiple: true
